---
# LINUX
- name: Install common packages
  package: name={{ item }}
  with_items:
    - unzip
  when: ansible_system == "Linux"
  
- name: Fetch and unpack Consul distribution
  unarchive:
    dest: /usr/bin
    copy: no
    src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
    mode: 0755
    creates: /usr/bin/consul
  when: ansible_system == "Linux"

- name: Create Consul directories
  file: path={{ item }} state=directory mode=0755
  with_items:
    - /etc/consul.d
    - /var/lib/consul
  when: ansible_system == "Linux"

- name: Template agent config (server mode)
  template:
    dest: "/etc/consul.d/agent.json"
    src: "consul.json.tmpl" 
  notify: restart consul agent
  when:
    - ansible_system == "Linux"
    - consul_mode == "server"

- name: Template agent config (client mode)
  template:
    dest: "/etc/consul.d/agent.json"
    src: "client.json.tmpl" 
  notify: restart consul agent
  when:
    - ansible_system == "Linux"
    - consul_mode == "client"

- name: Template systemd service config
  template:
    dest: "/etc/systemd/system/consul.service"
    src: systemd-consul.tmpl
  notify: restart consul agent
  when: ansible_system == "Linux"

- name: Start Consul agent service
  service: name=consul state=started enabled=yes
  when: ansible_system == "Linux"

# WINDOWS
- name: Windows - Configure directories
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "C:\\consul\\bin"
    - "C:\\consul\\data"
    - "C:\\consul\\conf"
  when: ansible_system == "Windows"

- name: Windows - Download Consul binaries
  win_get_url: 
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_windows_amd64.zip"
    dest: "C:\\installs\\consul-{{ consul_version }}.zip"
  when: ansible_system == "Windows"

- name: Windows - Install Consul
  win_unzip:
    src: "C:\\installs\\consul-{{ consul_version }}.zip"
    dest: "C:\\consul\\bin"
    creates: "C:\\consul\\bin\\consul.exe"
    rm: false
  when: ansible_system == "Windows"
  
- name: Windows - Template out config files
  win_template: src="client-win.json.tmpl" dest="C:\\consul\\conf\\consul.json"
  when: ansible_system == "Windows"

- name: Windows - Install nssm
  win_chocolatey: name=nssm state=present allow_empty_checksums=true
  when: ansible_system == "Windows"

- name: Windows - Create consul service
  win_nssm:
    name: Consul
    application: "C:\\consul\\bin\\consul.exe"
    app_parameters:
      _: agent
      "-config-dir": C:\consul\conf
    start_mode: auto
    state: started
  when: ansible_system == "Windows"
