---
- hosts: all
  name: global configuration
  gather_facts: true
  become: true

  roles:
    - updates

- hosts: consul-server
  name: Install and configure Consul
  gather_facts: true
  become: true

  roles:
    - consul

- hosts: nomad-server
  name: Install and configure Nomad
  gather_facts: true
  become: true

  roles:
    - nomad
    - docker-compose
    - filebeat