---
- hosts: consul-server
  name: Install and configure Consul
  gather_facts: true

  roles:
    - consul

  vars:
    consul_mode: server

- hosts: consul-client
  name: Install and configure Consul client
  gather_facts: true

  roles:
    - consul

- hosts: nomad-server
  name: Install and configure Nomad
  gather_facts: true

  roles:
    - nomad
    - docker-compose
    - filebeat
