---
- hosts: consul-server
  name: Install and configure Consul
  gather_facts: true

  roles:
    - consul

  vars:
    consul_mode: server

- hosts: consul-client
  name: Install and configure Consul client
  gather_facts: true

  roles:
    - consul

- hosts: nomad-server
  name: Install and configure Nomad
  gather_facts: true

  roles:
    - nomad
    - docker
    - docker-compose
    - filebeat

  vars:
    - nomad_server: true

- hosts: nomad-client:&windows
  name: Install and configure Nomad client
  gather_facts: true

  roles:
    - nomad

- hosts: nomad-client:&linux
  name: Install and configure Linux Nomad clients
  gather_facts: true

  roles:
    - nomad
    - docker
    - filebeat

