---
- name: Install common packages
  package: name={{ item }}
  with_items:
    - unzip
  when: ansible_system == "Linux"

- name: Fetch and unpack Nomad distribution
  unarchive:
    dest: /usr/bin
    copy: no
    src: "https://releases.hashicorp.com/nomad/0.4.0/nomad_0.4.0_linux_amd64.zip"
    mode: 0755
    creates: /usr/bin/nomad
  when: ansible_system == "Linux"

- name: Create Nomad directories
  file: path={{ item }} state=directory mode=0755
  with_items:
    - /etc/nomad.d
    - /var/lib/nomad
  when: ansible_system == "Linux"

- name: Template server.hcl
  template:
    dest: "/etc/nomad.d/server.hcl"
    src: server.hcl.tmpl
  when: ansible_system == "Linux"

- name: Template client.hcl
  template:
    dest: "/etc/nomad.d/client.hcl"
    src: client.hcl.tmpl
  when: ansible_system == "Linux"

- name: Template nomad systemd service config
  template:
    dest: "/etc/systemd/system/nomad.service"
    src: systemd-nomad.tmpl
  when: ansible_system == "Linux"

- name: Start Nomad agent service
  service: name=nomad state=started enabled=yes
  when: ansible_system == "Linux"
  
# Create some example job template files

- name: Template logs job file
  template:
    dest: "/home/alang021/logs.nomad"
    src: logs.nomad.tmpl
  when: ansible_system == "Linux"

- name: Template beacon job file
  template:
    dest: "/home/alang021/beacon.nomad"
    src: beacon.nomad.tmpl
  when: ansible_system == "Linux"